# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

blv <- function(costs, X, alpha, beta, Z_init, epsilon, iter_max, conv_check, precision, quadratic) {
    .Call(`_blvim_blv`, costs, X, alpha, beta, Z_init, epsilon, iter_max, conv_check, precision, quadratic)
}

we_oc <- function(costs, X, alpha, beta, Z) {
    .Call(`_blvim_we_oc`, costs, X, alpha, beta, Z)
}

