# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

we_oc <- function(costs, X, alpha, beta, Z) {
    .Call(`_blvim_we_oc`, costs, X, alpha, beta, Z)
}

